declare global {
  namespace NodeJS {
    interface ProcessEnv {
      CREDENTIAL_BAIKAL_USERNAME: string;
      CREDENTIAL_BAIKAL_PASSWORD: string;
      CREDENTIAL_BAIKAL_SERVER_URL: string;
      CREDENTIAL_NEXTCLOUD_USERNAME: string;
      CREDENTIAL_NEXTCLOUD_PASSWORD: string;
      CREDENTIAL_NEXTCLOUD_SERVER_URL: string;
      CREDENTIAL_FASTMAIL_USERNAME: string;
      CREDENTIAL_FASTMAIL_APP_PASSWORD: string;
      CREDENTIAL_ICLOUD_USERNAME: string;
      CREDENTIAL_ICLOUD_APP_SPECIFIC_PASSWORD: string;
      CREDENTIAL_GOOGLE_USERNAME: string;
      CREDENTIAL_GOOGLE_REFRESH_TOKEN: string;
      CREDENTIAL_GOOGLE_CLIENT_ID: string;
      CREDENTIAL_GOOGLE_CLIENT_SECRET: string;
      RECORD_NETWORK_REQUESTS: string;
      MOCK_FETCH: string;
    }
  }
}

export {};
